// <auto-generated />
using System;
using Advanced_Database_and_ORM_Concepts_Assignment_1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Advanced_Database_and_ORM_Concepts_Assignment_1.Migrations
{
    [DbContext(typeof(Advanced_Database_and_ORM_Concepts_Assignment_1Context))]
    [Migration("20230321174838_Validation")]
    partial class Validation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PodcastId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("PodcastId");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AirDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("PodcastId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PodcastId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.LibrarySong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LibrarySongs");
                });

            modelBuilder.Entity("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.ListenerList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ListenerListName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("ListenerList");
                });

            modelBuilder.Entity("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.PlaylistSong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlaylistId")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeAdded")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("SongId");

                    b.ToTable("PlaylistSongs");
                });

            modelBuilder.Entity("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.Podcast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PodcastTitle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Podcast");
                });

            modelBuilder.Entity("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.SongContributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("SongId");

                    b.ToTable("SongContributors");
                });

            modelBuilder.Entity("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ListenerListPodcast", b =>
                {
                    b.Property<int>("ListenerListsId")
                        .HasColumnType("int");

                    b.Property<int>("PodcastsId")
                        .HasColumnType("int");

                    b.HasKey("ListenerListsId", "PodcastsId");

                    b.HasIndex("PodcastsId");

                    b.ToTable("ListenerListPodcast");
                });

            modelBuilder.Entity("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.Artist", b =>
                {
                    b.HasOne("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.Episode", null)
                        .WithMany("GuestArtists")
                        .HasForeignKey("EpisodeId");

                    b.HasOne("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.Podcast", null)
                        .WithMany("Artists")
                        .HasForeignKey("PodcastId");
                });

            modelBuilder.Entity("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.Episode", b =>
                {
                    b.HasOne("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.Podcast", null)
                        .WithMany("Episodes")
                        .HasForeignKey("PodcastId");
                });

            modelBuilder.Entity("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.PlaylistSong", b =>
                {
                    b.HasOne("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.Playlist", "Playlist")
                        .WithMany("PlaylistSongs")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.Song", "Song")
                        .WithMany("PlaylistSongs")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.Song", b =>
                {
                    b.HasOne("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.SongContributor", b =>
                {
                    b.HasOne("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.Artist", "Artist")
                        .WithMany("SongContributors")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.Song", "Song")
                        .WithMany("SongContributors")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("ListenerListPodcast", b =>
                {
                    b.HasOne("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.ListenerList", null)
                        .WithMany()
                        .HasForeignKey("ListenerListsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.Podcast", null)
                        .WithMany()
                        .HasForeignKey("PodcastsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.Album", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.Artist", b =>
                {
                    b.Navigation("SongContributors");
                });

            modelBuilder.Entity("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.Episode", b =>
                {
                    b.Navigation("GuestArtists");
                });

            modelBuilder.Entity("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.Playlist", b =>
                {
                    b.Navigation("PlaylistSongs");
                });

            modelBuilder.Entity("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.Podcast", b =>
                {
                    b.Navigation("Artists");

                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("Advanced_Database_and_ORM_Concepts_Assignment_1.Models.Song", b =>
                {
                    b.Navigation("PlaylistSongs");

                    b.Navigation("SongContributors");
                });
#pragma warning restore 612, 618
        }
    }
}
